# Generated by Django 4.2.15 on 2024-09-15 10:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bashkite_2014',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.IntegerField(blank=True, null=True)),
                ('gid', models.IntegerField(blank=True, null=True)),
                ('id_bash', models.IntegerField(blank=True, null=True, unique=True)),
                ('emer_bash', models.CharField(blank=True, max_length=100, null=True)),
                ('qender_bash', models.CharField(blank=True, max_length=100, null=True)),
                ('id_qark', models.IntegerField(blank=True, null=True)),
                ('emer_qark', models.CharField(blank=True, max_length=100, null=True)),
                ('qender_qark', models.CharField(blank=True, max_length=100, null=True)),
                ('pop_2011', models.IntegerField(blank=True, null=True)),
                ('pop_rgjcv', models.IntegerField(blank=True, null=True)),
                ('den_instat', models.FloatField(blank=True, null=True)),
                ('sip', models.FloatField(blank=True, null=True)),
                ('shape_length', models.FloatField(blank=True, null=True)),
                ('shape_area', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'verbose_name_plural': 'bashkite_2014',
                'db_table': 'bashkite_2014',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='applog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('object', models.CharField(blank=True, max_length=100, null=True)),
                ('time', models.DateTimeField()),
                ('operation', models.CharField(max_length=10)),
                ('objectid', models.IntegerField()),
                ('objectpk', models.CharField(blank=True, max_length=100, null=True)),
                ('tablename', models.CharField(blank=True, max_length=100, null=True)),
                ('tableid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'applog',
                'db_table': 'applog',
            },
        ),
        migrations.CreateModel(
            name='blockgrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_comment="Combination of row position as letters ('A' to 'J') and column position as numbers ('01' to '10')", max_length=3)),
                ('rownum', models.IntegerField(blank=True, db_comment='Row number within the map sheet from the top', null=True)),
                ('colnum', models.IntegerField(blank=True, db_comment='Column number within the map sheet from the leftmost.', null=True)),
                ('the_geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('mapcode', models.CharField(blank=True, db_comment='Code of map sheet.', max_length=4, null=True)),
            ],
            options={
                'verbose_name': 'blockgrid',
                'db_table': 'blockgrid',
            },
        ),
        migrations.CreateModel(
            name='cultivationform',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'cultivationform',
                'db_table': 'cultivationform',
                'ordering': ['code', 'description'],
            },
        ),
        migrations.CreateModel(
            name='cultivationtype',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'cultivationtype',
                'db_table': 'cultivationtype',
                'ordering': ['code', 'description'],
            },
        ),
        migrations.CreateModel(
            name='exposure',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'exposure',
                'db_table': 'exposure',
                'ordering': ['code', 'description'],
            },
        ),
        migrations.CreateModel(
            name='inclination',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'inclination',
                'ordering': ['code', 'description'],
            },
        ),
        migrations.CreateModel(
            name='irrigationtype',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'irrigationtype',
                'db_table': 'irrigationtype',
                'ordering': ['code', 'description'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='mechanizationtype',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'mechanizationtype',
                'ordering': ['code', 'description'],
            },
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('secondname', models.CharField(blank=True, max_length=30, null=True)),
                ('fathername', models.CharField(blank=True, max_length=30, null=True)),
                ('birthdate', models.DateField()),
                ('code', models.CharField(blank=True, db_comment='Code used only to identify surveyors', max_length=10, null=True)),
                ('legal', models.BooleanField(blank=True, db_comment='Is this a legal (as opposed to physical) person ?', null=True)),
            ],
            options={
                'verbose_name_plural': 'persons',
                'db_table': 'person',
                'db_table_comment': 'A human being.',
            },
        ),
        migrations.CreateModel(
            name='productiontype',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'productiontype',
                'ordering': ['code', 'description'],
            },
        ),
        migrations.CreateModel(
            name='qarqet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.IntegerField(blank=True, null=True)),
                ('id_qark', models.IntegerField(blank=True, null=True, unique=True)),
                ('emer_qark', models.CharField(blank=True, max_length=100, null=True)),
                ('qend_qark', models.CharField(blank=True, max_length=100, null=True)),
                ('shape_length', models.FloatField(blank=True, null=True)),
                ('shape_area', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=32634)),
            ],
            options={
                'verbose_name_plural': 'qarqet',
                'db_table': 'qarqet',
                'ordering': ['id_qark', 'emer_qark'],
            },
        ),
        migrations.CreateModel(
            name='referencegrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_comment="Combination of row position as letters (from 'A' to 'J') and column position as number.", max_length=4, unique=True)),
                ('the_geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('colnum', models.IntegerField(blank=True, null=True)),
                ('rownum', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'referencegrid',
                'db_table': 'referencegrid',
            },
        ),
        migrations.CreateModel(
            name='rocktype',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name_plural': 'rocktype',
                'db_table': 'rocktype',
                'ordering': ['code', 'description'],
            },
        ),
        migrations.CreateModel(
            name='rootstock',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=80, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'rootstock',
                'db_table': 'rootstock',
                'ordering': ['code', 'description'],
            },
        ),
        migrations.CreateModel(
            name='rowsdirection',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'rowsdirection',
                'db_table': 'rowsdirection',
                'ordering': ['code', 'description'],
            },
        ),
        migrations.CreateModel(
            name='rowsdirectiontype',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'rowsdirectiontype',
                'db_table': 'rowsdirectiontype',
                'ordering': ['code', 'description'],
            },
        ),
        migrations.CreateModel(
            name='soildepth',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'soildepth',
                'db_table': 'soildepth',
                'ordering': ['code', 'description'],
            },
        ),
        migrations.CreateModel(
            name='soiltype',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=80, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'soiltype',
                'db_table': 'soiltype',
                'ordering': ['code', 'description'],
            },
        ),
        migrations.CreateModel(
            name='supporttype',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'supporttype',
                'db_table': 'supporttype',
                'ordering': ['code', 'description'],
            },
        ),
        migrations.CreateModel(
            name='surveystate',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'surveystate',
                'ordering': ['code', 'description'],
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, db_comment='emri i deklaruesit', max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, db_comment='mbiemri i deklaruesit', max_length=50, null=True)),
                ('email', models.CharField(blank=True, db_comment='emaili zyrtar i deklaruesit.', max_length=255, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('current_login_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_ip', models.CharField(blank=True, max_length=25, null=True)),
                ('current_login_ip', models.CharField(blank=True, max_length=25, null=True)),
                ('login_count', models.IntegerField(blank=True, null=True)),
                ('fs_uniquifier', models.CharField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'user',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='variety',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=80)),
                ('registercode', models.CharField(blank=True, db_comment='Code used in the variety register, if any.', max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'variety',
                'db_table': 'variety',
            },
        ),
        migrations.CreateModel(
            name='varietypurity',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'varietypurity',
                'db_table': 'varietypurity',
                'ordering': ['code', 'description'],
            },
        ),
        migrations.CreateModel(
            name='villages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.IntegerField(blank=True, null=True)),
                ('code', models.BigIntegerField(unique=True)),
                ('emri_zk', models.CharField(blank=True, max_length=60, null=True)),
                ('id_bash', models.CharField(blank=True, max_length=50, null=True)),
                ('emer_bash', models.CharField(blank=True, max_length=100, null=True)),
                ('qend_bash', models.CharField(blank=True, max_length=100, null=True)),
                ('id_qark', models.CharField(blank=True, max_length=50, null=True)),
                ('emer_qark', models.CharField(blank=True, max_length=100, null=True)),
                ('qend_qark', models.CharField(blank=True, max_length=100, null=True)),
                ('id_njqv', models.IntegerField(blank=True, null=True)),
                ('emer_njqv', models.CharField(blank=True, max_length=50, null=True)),
                ('emri_nga_tabela_village', models.CharField(blank=True, max_length=50, null=True)),
                ('id_rrethi', models.IntegerField(blank=True, null=True)),
                ('emer_rrethi', models.CharField(blank=True, max_length=50, null=True)),
                ('shape_area', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'verbose_name_plural': 'villages',
                'db_table': 'villages',
                'ordering': ['emer_bash', 'emer_njqv'],
            },
        ),
        migrations.CreateModel(
            name='vineyardunit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapcode', models.CharField(db_comment='Code of map sheet as in the nation-wide grid.', max_length=4)),
                ('blockcode', models.CharField(db_comment='Code of block within a map sheet.', max_length=3)),
                ('farmcode', models.CharField(blank=True, db_comment="Code of unit's owner enterprise in the registry of farms.", max_length=20, null=True)),
                ('fiscalcode', models.CharField(blank=True, db_comment="Tax code of the unit's owner.", max_length=20, null=True)),
                ('altitude', models.IntegerField(blank=True, db_comment='Altitude of parcle in meters', null=True)),
                ('erosion', models.BooleanField(blank=True, db_comment='Presence of erosion.', null=True)),
                ('surface', models.FloatField(blank=True, db_comment='Surface of unit in square meters.', null=True)),
                ('rowsdistance', models.FloatField(blank=True, db_comment='Distance in centimeters between rows of plants.', null=True)),
                ('plantsdistance', models.FloatField(blank=True, db_comment='Distance in centimeters between plsnts belonging to the same row.', null=True)),
                ('couplesdistance', models.FloatField(blank=True, db_comment='Distance in centimeters between plants planted in couples.', null=True)),
                ('mincultivationheight', models.FloatField(blank=True, db_comment='Minimum cultivation height in centimeters.', null=True)),
                ('maxcultivationheight', models.FloatField(blank=True, db_comment='Maximum cultivation height in centimeters.', null=True)),
                ('notes', models.TextField(blank=True, db_comment='Type of other grape variety.', null=True)),
                ('principalvarietyperc', models.IntegerField(blank=True, db_comment='Percentage of plant of the principal grape variety.', null=True)),
                ('secondaryvarietyperc', models.IntegerField(blank=True, db_comment='Percentage of plant of the secondary grape variety.', null=True)),
                ('othervarietyperc', models.IntegerField(blank=True, db_comment='Percentage of plants of the other grape variety.', null=True)),
                ('the_geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, db_comment='Geometry of the vineyard unit (a polygon)', null=True, srid=4326)),
                ('surveydate', models.DateField(blank=True, db_comment='Date of survey.', null=True)),
                ('unitcode', models.IntegerField(blank=True, db_comment='Unique code of vineyard unit within the block.', null=True)),
                ('surveycode', models.CharField(blank=True, db_comment='Code used during the survey to identify the vineyard unit.', max_length=30, null=True)),
                ('implantationyear', models.IntegerField(blank=True, db_comment='Year of vineyard implantation', null=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('flag', models.IntegerField(blank=True, null=True)),
                ('area', models.IntegerField(blank=True, db_comment='area of polygon', null=True)),
                ('bashkia', models.ForeignKey(blank=True, db_column='bashkia', db_comment='code of municipality', null=True, on_delete=django.db.models.deletion.CASCADE, to='winecadapp.bashkite_2014', to_field='id_bash')),
                ('cultivationform', models.ForeignKey(blank=True, db_column='cultivationform', db_comment='Form of cultivation and pruning.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='winecadapp.cultivationform')),
                ('cultivationtype', models.ForeignKey(blank=True, db_column='cultivationtype', db_comment='Cultivation type  and relation to other crop/orchard types.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='winecadapp.cultivationtype')),
                ('exposure', models.ForeignKey(blank=True, db_column='exposure', db_comment='Facing of vineyard unit.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='winecadapp.exposure')),
                ('fshati', models.ForeignKey(blank=True, db_column='fshati', db_comment='code of village', null=True, on_delete=django.db.models.deletion.CASCADE, to='winecadapp.villages', to_field='code')),
                ('inclination', models.ForeignKey(blank=True, db_column='inclination', db_comment='Class of inclination.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='winecadapp.inclination')),
                ('irrigationtype', models.ForeignKey(blank=True, db_column='irrigationtype', db_comment='Type of irrigation (left empty if non-irrigated).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='winecadapp.irrigationtype')),
                ('mechanizationtype', models.ForeignKey(blank=True, db_column='mechanizationtype', db_comment='Type of vineyard unit mechanization.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='winecadapp.mechanizationtype')),
                ('othervariety', models.ForeignKey(blank=True, db_column='othervariety', db_comment='Type of other grape variety.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vineyardunit_othervariety_set', to='winecadapp.variety')),
                ('prevsoiltype', models.ForeignKey(blank=True, db_column='prevsoiltype', db_comment='Prevalent soil type on which the unit is located.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='winecadapp.soiltype')),
                ('principalvariety', models.ForeignKey(blank=True, db_column='principalvariety', db_comment='Type of principal variety.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='winecadapp.variety')),
                ('qarku', models.ForeignKey(blank=True, db_column='qarku', db_comment='code of region', null=True, on_delete=django.db.models.deletion.CASCADE, to='winecadapp.qarqet', to_field='id_qark')),
                ('rootstocktype', models.ForeignKey(blank=True, db_column='rootstocktype', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='winecadapp.rootstock')),
                ('rowsdirection', models.ForeignKey(blank=True, db_column='rowsdirection', db_comment='General direction of rows', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='winecadapp.rowsdirection')),
                ('secondaryvariety', models.ForeignKey(blank=True, db_column='secondaryvariety', db_comment='Type of secondary grape variety.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vineyardunit_secondaryvariety_set', to='winecadapp.variety')),
                ('soildepth', models.ForeignKey(blank=True, db_column='soildepth', db_comment='Class of soil depth.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='winecadapp.soildepth')),
                ('supportsystem', models.ForeignKey(blank=True, db_column='supportsystem', db_comment='Plant support system type.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='winecadapp.supporttype')),
                ('surveyor', models.ForeignKey(blank=True, db_column='surveyor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='winecadapp.person')),
                ('surveystate', models.ForeignKey(blank=True, db_column='surveystate', db_comment='State of vineyard unit in survey.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='winecadapp.surveystate')),
                ('varietypurity', models.ForeignKey(blank=True, db_column='varietypurity', db_comment='Grade of purity of the grape variety.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='winecadapp.varietypurity')),
            ],
            options={
                'verbose_name_plural': 'vineyardunit',
                'db_table': 'vineyardunit',
                'ordering': ['qarku', 'bashkia', 'fshati', 'id'],
                'unique_together': {('mapcode', 'blockcode', 'unitcode')},
            },
        ),
        migrations.AddField(
            model_name='person',
            name='village',
            field=models.ForeignKey(blank=True, db_column='village', db_comment='Village of residence.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='winecadapp.villages', to_field='code'),
        ),
        migrations.CreateModel(
            name='vineyardunittenant',
            fields=[
                ('vineyardunit', models.OneToOneField(db_column='vineyardunit', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='winecadapp.vineyardunit')),
                ('tenant', models.ForeignKey(db_column='tenant', on_delete=django.db.models.deletion.DO_NOTHING, to='winecadapp.person')),
            ],
            options={
                'verbose_name_plural': 'vineyardunittenant',
                'db_table': 'vineyardunittenant',
                'unique_together': {('vineyardunit', 'tenant')},
            },
        ),
        migrations.CreateModel(
            name='vineyardunitsoiltype',
            fields=[
                ('vineyardunit', models.OneToOneField(db_column='vineyardunit', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='winecadapp.vineyardunit')),
                ('type', models.IntegerField(blank=True, db_comment='Type of soil type for vineyarsd unit: 1 prmary: 2 secondary.', null=True)),
                ('soiltype', models.ForeignKey(db_column='soiltype', on_delete=django.db.models.deletion.DO_NOTHING, to='winecadapp.soiltype')),
            ],
            options={
                'verbose_name_plural': 'vineyardunitsoiltype',
                'db_table': 'vineyardunitsoiltype',
                'unique_together': {('vineyardunit', 'soiltype')},
            },
        ),
        migrations.CreateModel(
            name='vineyardunitrocktype',
            fields=[
                ('vineyardunit', models.OneToOneField(db_column='vineyardunit', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='winecadapp.vineyardunit')),
                ('rocktype', models.ForeignKey(db_column='rocktype', on_delete=django.db.models.deletion.DO_NOTHING, to='winecadapp.rocktype')),
            ],
            options={
                'verbose_name_plural': 'vineyardunitrocktype',
                'db_table': 'vineyardunitrocktype',
                'unique_together': {('vineyardunit', 'rocktype')},
            },
        ),
        migrations.CreateModel(
            name='vineyardunitproduction',
            fields=[
                ('vineyardunit', models.OneToOneField(db_column='vineyardunit', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='winecadapp.vineyardunit')),
                ('productiontype', models.ForeignKey(db_column='productiontype', on_delete=django.db.models.deletion.DO_NOTHING, to='winecadapp.productiontype')),
            ],
            options={
                'verbose_name_plural': 'vineyardunitproduction',
                'db_table': 'vineyardunitproduction',
                'unique_together': {('vineyardunit', 'productiontype')},
            },
        ),
        migrations.CreateModel(
            name='vineyardunitowner',
            fields=[
                ('owner', models.OneToOneField(db_column='owner', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='winecadapp.person')),
                ('vineyardunit', models.ForeignKey(db_column='vineyardunit', on_delete=django.db.models.deletion.CASCADE, to='winecadapp.vineyardunit')),
            ],
            options={
                'verbose_name_plural': 'vineyardunitowner',
                'db_table': 'vineyardunitowner',
                'unique_together': {('owner', 'vineyardunit')},
            },
        ),
        migrations.CreateModel(
            name='vaniardunittenant',
            fields=[
                ('vineyardunit', models.OneToOneField(db_column='vineyardunit', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='winecadapp.vineyardunit')),
                ('owner', models.ForeignKey(db_column='owner', on_delete=django.db.models.deletion.DO_NOTHING, to='winecadapp.person')),
            ],
            options={
                'verbose_name_plural': 'vaniard unit tenant',
                'db_table': 'vaniardunittenant',
                'unique_together': {('vineyardunit', 'owner')},
            },
        ),
    ]
