# Generated by Django 4.2.15 on 2024-09-17 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('winecadapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vineyardunit',
            name='bashkia',
            field=models.ForeignKey(blank=True, db_column='bashkia', db_comment='code of municipality', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='winecadapp.bashkite_2014', to_field='id_bash'),
        ),
        migrations.AlterField(
            model_name='vineyardunit',
            name='fshati',
            field=models.ForeignKey(blank=True, db_column='fshati', db_comment='code of village', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='winecadapp.villages', to_field='code'),
        ),
        migrations.AlterField(
            model_name='vineyardunit',
            name='qarku',
            field=models.ForeignKey(blank=True, db_column='qarku', db_comment='code of region', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='winecadapp.qarqet', to_field='id_qark'),
        ),
        migrations.AlterField(
            model_name='vineyardunit',
            name='surveydate',
            field=models.DateTimeField(blank=True, db_comment='Date of survey.', null=True),
        ),
    ]
