# Generated by Django 4.2.15 on 2024-11-07 14:54

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "winecadapp",
            "0002_alter_vineyardunit_bashkia_alter_vineyardunit_fshati_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="totalrowsvineyardalbania",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "qarku",
                    models.CharField(
                        blank=True, db_column="Qarku", max_length=100, null=True
                    ),
                ),
                (
                    "bashkia",
                    models.CharField(
                        blank=True, db_column="Bashkia", max_length=100, null=True
                    ),
                ),
                (
                    "fshati",
                    models.CharField(
                        blank=True, db_column="Fshati", max_length=60, null=True
                    ),
                ),
                (
                    "kodi_i_hartes",
                    models.CharField(
                        blank=True, db_column="Kodi i Hartes", max_length=4, null=True
                    ),
                ),
                (
                    "blloku",
                    models.CharField(
                        blank=True, db_column="Blloku", max_length=3, null=True
                    ),
                ),
                ("kodiparceles", models.IntegerField(blank=True, null=True)),
                (
                    "pronari",
                    models.TextField(blank=True, db_column="Pronari", null=True),
                ),
                (
                    "perdoruesi",
                    models.TextField(blank=True, db_column="Perdoruesi", null=True),
                ),
                (
                    "kodi_i_fermes",
                    models.CharField(
                        blank=True, db_column="Kodi i Fermes", max_length=20, null=True
                    ),
                ),
                (
                    "kodi_fiskal",
                    models.CharField(
                        blank=True, db_column="Kodi Fiskal", max_length=20, null=True
                    ),
                ),
                (
                    "gjendja_e_vreshtit",
                    models.CharField(
                        blank=True,
                        db_column="Gjendja e vreshtit",
                        max_length=80,
                        null=True,
                    ),
                ),
                (
                    "data_e_vrojtimit",
                    models.TextField(
                        blank=True, db_column="Data e vrojtimit", null=True
                    ),
                ),
                (
                    "latesia_nga_deti",
                    models.IntegerField(
                        blank=True, db_column="Latesia nga deti", null=True
                    ),
                ),
                (
                    "erozioni",
                    models.BooleanField(blank=True, db_column="Erozioni", null=True),
                ),
                (
                    "siperfaqja",
                    models.FloatField(blank=True, db_column="Siperfaqja", null=True),
                ),
                (
                    "siperfaqja_ne_ha",
                    models.FloatField(
                        blank=True, db_column="Siperfaqja ne HA", null=True
                    ),
                ),
                (
                    "siperfaqja_faktike",
                    models.IntegerField(
                        blank=True, db_column="Siperfaqja faktike", null=True
                    ),
                ),
                (
                    "viti_i_mbjelljes",
                    models.IntegerField(
                        blank=True, db_column="Viti i mbjelljes", null=True
                    ),
                ),
                (
                    "distanca_midis_rreshtave",
                    models.FloatField(
                        blank=True, db_column="Distanca midis rreshtave", null=True
                    ),
                ),
                (
                    "distanca_midis_bimeve",
                    models.FloatField(
                        blank=True, db_column="Distanca midis bimeve", null=True
                    ),
                ),
                (
                    "distanca_midis_cifteve",
                    models.FloatField(
                        blank=True, db_column="Distanca midis cifteve", null=True
                    ),
                ),
                (
                    "lloji_i_ujitjes",
                    models.CharField(
                        blank=True,
                        db_column="Lloji i ujitjes",
                        max_length=80,
                        null=True,
                    ),
                ),
                (
                    "pjerresia",
                    models.CharField(
                        blank=True, db_column="Pjerresia", max_length=80, null=True
                    ),
                ),
                (
                    "mekanizimi",
                    models.CharField(
                        blank=True, db_column="Mekanizimi", max_length=80, null=True
                    ),
                ),
                (
                    "drejtimi_i_rreshtave",
                    models.CharField(
                        blank=True,
                        db_column="Drejtimi i Rreshtave",
                        max_length=80,
                        null=True,
                    ),
                ),
                (
                    "ekspozimi",
                    models.CharField(
                        blank=True, db_column="Ekspozimi", max_length=80, null=True
                    ),
                ),
                (
                    "tipi_i_kultivimit",
                    models.CharField(
                        blank=True,
                        db_column="Tipi i kultivimit",
                        max_length=80,
                        null=True,
                    ),
                ),
                (
                    "thellesi_e_tokes",
                    models.CharField(
                        blank=True,
                        db_column="Thellesi e Tokes",
                        max_length=80,
                        null=True,
                    ),
                ),
                (
                    "tipi_i_tokes_meparshme",
                    models.CharField(
                        blank=True,
                        db_column="Tipi i tokes meparshme",
                        max_length=80,
                        null=True,
                    ),
                ),
                (
                    "shkembi_amnor",
                    models.TextField(blank=True, db_column="Shkembi amnor", null=True),
                ),
                (
                    "tipi_i_tokes",
                    models.TextField(blank=True, db_column="Tipi i tokes", null=True),
                ),
                (
                    "lartesia_mumimale_e_kultivimit",
                    models.FloatField(
                        blank=True,
                        db_column="Lartesia mumimale e Kultivimit",
                        null=True,
                    ),
                ),
                (
                    "lartesia_maksimale_e_kultivimit",
                    models.FloatField(
                        blank=True,
                        db_column="Lartesia maksimale e Kultivimit",
                        null=True,
                    ),
                ),
                (
                    "destinacioni_i_prodhimit",
                    models.TextField(
                        blank=True, db_column="Destinacioni i prodhimit", null=True
                    ),
                ),
                (
                    "forma_e_kultivimit",
                    models.CharField(
                        blank=True,
                        db_column="Forma e Kultivimit",
                        max_length=80,
                        null=True,
                    ),
                ),
                (
                    "tipi_i_mbeshtetjes",
                    models.CharField(
                        blank=True,
                        db_column="Tipi i mbeshtetjes",
                        max_length=80,
                        null=True,
                    ),
                ),
                (
                    "pastertia_variotore",
                    models.CharField(
                        blank=True,
                        db_column="Pastertia variotore",
                        max_length=80,
                        null=True,
                    ),
                ),
                (
                    "varieteti_kryesor",
                    models.CharField(
                        blank=True,
                        db_column="Varieteti kryesor",
                        max_length=80,
                        null=True,
                    ),
                ),
                (
                    "perqindja_e_varietetit_kryesor",
                    models.IntegerField(
                        blank=True,
                        db_column="Perqindja e varietetit kryesor",
                        null=True,
                    ),
                ),
                (
                    "varieteti_dytesor",
                    models.CharField(
                        blank=True,
                        db_column="Varieteti dytesor",
                        max_length=80,
                        null=True,
                    ),
                ),
                (
                    "field_perqindja_e_varietetit_dytesor",
                    models.IntegerField(
                        blank=True,
                        db_column=" Perqindja e varietetit dytesor",
                        null=True,
                    ),
                ),
                (
                    "varietet_tjeter",
                    models.CharField(
                        blank=True,
                        db_column="Varietet tjeter",
                        max_length=80,
                        null=True,
                    ),
                ),
                (
                    "perqindja_e_varieteteve_te_tjere",
                    models.IntegerField(
                        blank=True,
                        db_column="Perqindja e varieteteve te tjere",
                        null=True,
                    ),
                ),
                (
                    "nenshartesa",
                    models.CharField(
                        blank=True, db_column="Nenshartesa", max_length=80, null=True
                    ),
                ),
                (
                    "shenime",
                    models.TextField(blank=True, db_column="Shenime", null=True),
                ),
                (
                    "the_geom",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "survejues",
                    models.TextField(blank=True, db_column="Survejues", null=True),
                ),
            ],
            options={
                "db_table": "total_rows_vineyard_albania",
                "managed": False,
            },
        ),
        migrations.AlterField(
            model_name="person",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="vineyardunit",
            name="surveydate",
            field=models.DateField(
                blank=True,
                db_comment="Date of survey.",
                default=datetime.date.today,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vineyardunit",
            name="surveyor",
            field=models.ForeignKey(
                blank=True,
                db_column="surveyor",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="winecadapp.person",
            ),
        ),
    ]
