# Generated by Django 3.2 on 2024-08-22 15:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vineyardunit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapcode', models.CharField(max_length=4)),
                ('blockcode', models.CharField(max_length=3)),
                ('unitcode', models.IntegerField()),
                ('farmcode', models.CharField(max_length=20)),
                ('fiscalcode', models.CharField(max_length=20)),
                ('geom_point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Vineyardunits',
            },
        ),
    ]
