"""
Django settings for winecad project.

Generated by 'django-admin startproject' using Django 4.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

 
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a4bvevc00#2zbe=w7qyd(t_xx&e6q4&5em&*%994h(=z2l1(-)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'leaflet',
    'djgeojson',
    'mapwidgets',
    'winecadapp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'winecad.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
              
            ],
        },
    },
]

WSGI_APPLICATION = 'winecad.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
""" 
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
} """

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME':   'winecaddb',#'winecadnewuser', #
        'USER':   'postgres',
        'PASSWORD':   'P1g0l1n0',
        'HOST': '127.0.0.1',
        'PORT':   5432,
    }}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

GEOS_LIBRARY_PATH = r'C:\OSGeo4W\bin\geos_c'
GDAL_LIBRARY_PATH  = r'C:\OSGeo4W\bin\gdal309'

SERIALIZATION_MODULE={
    'geojson':'djgeojson.serializers'
}
 
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

""" var orthophoto_2015 = L.tileLayer.wms('https://geoportal.asig.gov.al/service/wms', 
        {
        layers: 'orthophoto_2015:OrthoImagery_20cm',
        transparent: true,
        "tiled": true,
        "format": "image/png",
        }
    ) ;  """

LEAFLET_CONFIG = {
    # conf here
'DEFAULT_CENTER': (41, 20),
'DEFAULT_ZOOM': 16,
'MIN_ZOOM': 3,
'MAX_ZOOM': 18,
'DEFAULT_PRECISION': 6,
'TILES': [('ESRI Satellite', 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}', {'attribution': '&copy; ISB', 'maxZoom': 16}),
          ('Streets', 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {'attribution': '&copy; Contributors'})]
}
#'TILES': 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png'
#https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MAP_WIDGETS = {
    "GoogleMap": {
        "apiKey": 'AIzaSyA5g6bFK2t-0zQbCGT-uy_owEDm07_2oBc', #GOOGLE_MAP_API_KEY # General setting for all GoogleMap widgets
        "PointField": {   # GeoField type
            "interactive": {  # Specific settings for GoogleMap interactive PointField widget
                "mapOptions": {
                    "zoom": 15,
                },
                "GooglePlaceAutocompleteOptions": {
                    "componentRestrictions": {"country": "al"}
                },
                "mapCenterLocationName": "Tirana",
            }
        },
    },
    "Mapbox": {
        "accessToken": 'pk.eyJ1IjoiYmV4aGV0aXNsIiwiYSI6ImNrZng1ajE4MzA2aGwycm5reGkzcWZjZTUifQ.1EiXwgJKX2iEY4vzDmTj8w',#MAPBOX_ACCESS_TOKEN,
        "PointField": {
            "interactive": {
                "mapOptions": {"zoom": 12, "center": (40, 20)},
                "markerFitZoom": 14,
            }
        },
    },
    "is_dev_mode": False,  # Package global level setting for development mode
}
